-- CREATE TABLE
CREATE TABLE CAMERA
(
	ID             				NUMBER(18) NOT NULL,
	FRIENDLY_NAME				VARCHAR2(128) NULL,
	CONNECT_TO_HOST				CHAR(1) NULL,
	GPS_LATITUDE				NUMBER(38,30) NULL,
	GPS_LONGITUDE				NUMBER(38,30) NULL,
	LK_CAMERA_ADAPTER_TYPE		NUMBER NOT NULL,
	LK_CAMERA_CONNECTION_TYPE	NUMBER NOT NULL,
	LK_CAMERA_STATUS_TYPE		NUMBER NOT NULL,
	IS_ENABLED					CHAR(1) NULL,
	CONFIG_JSON					VARCHAR2(4000) NULL,
	CREATED_TIMESTAMP			DATE NOT NULL,
	MODIFIED_TIMESTAMP			DATE NULL
);
-- CREATE/RECREATE PRIMARY, UNIQUE AND FOREIGN KEY CONSTRAINTS 
ALTER TABLE CAMERA ADD CONSTRAINT CAMERA_PK PRIMARY KEY (ID) USING INDEX;

-- SEQUENCE
CREATE SEQUENCE  CAMERA_SEQ;

-- TRIGGER
CREATE OR REPLACE TRIGGER CAMERA_BI BEFORE INSERT ON CAMERA FOR EACH ROW
BEGIN
	:NEW.ID := CAMERA_SEQ.NEXTVAL;
END CAMERA_BI;
/