-- CREATE TABLE
CREATE TABLE USER
(
	ID             			NUMBER(18) NOT NULL,
	FIRST_NAME				VARCHAR2(128) NULL,
	LAST_NAME				VARCHAR2(128) NULL,
	MOBILE_NUMBER			VARCHAR2(64) NULL,	
	EMAIL					VARCHAR2(256) NOT NULL,
	CREATED_TIMESTAMP		DATE NOT NULL,
	USER_STATUS				INTEGER NOT NULL
);
-- CREATE/RECREATE PRIMARY, UNIQUE AND FOREIGN KEY CONSTRAINTS 
ALTER TABLE USER ADD CONSTRAINT USER_PK PRIMARY KEY (ID)  USING INDEX;

-- SEQUENCE
CREATE SEQUENCE  USER_SEQ;

-- TRIGGER
CREATE OR REPLACE TRIGGER USER_BI BEFORE INSERT ON USER FOR EACH ROW
BEGIN
	:NEW.ID := USER_SEQ.NEXTVAL;
END USER_BI;
/