-- CREATE TABLE
CREATE TABLE APPLICATION
(
	ID             			NUMBER(18) NOT NULL,
	NAME					VARCHAR2(512) NOT NULL,
	CREATED_TIMESTAMP		DATE NOT NULL,
	APPLICATION_STATUS		INTEGER NOT NULL
);
-- CREATE/RECREATE PRIMARY, UNIQUE AND FOREIGN KEY CONSTRAINTS 
ALTER TABLE APPLICATION ADD CONSTRAINT APPLICATION_PK PRIMARY KEY (ID)  USING INDEX;

-- SEQUENCE
CREATE SEQUENCE  APPLICATION_SEQ;

-- TRIGGER
CREATE OR REPLACE TRIGGER APPLICATION_BI BEFORE INSERT ON APPLICATION FOR EACH ROW
BEGIN
	:NEW.ID := APPLICATION_SEQ.NEXTVAL;
END APPLICATION_BI;
/