-- CREATE TABLE
CREATE TABLE USER_SESSION
(
	ID             			NUMBER(18) NOT NULL,
	TOKEN					VARCHAR2(512) NOT NULL,
	CREDENTIAL_ID			NUMBER(18) NOT NULL,	
	CREATED_TIMESTAMP		DATE NOT NULL,
	EXPIRY_TIMESTAMP		DATE NOT NULL
);
-- CREATE/RECREATE PRIMARY, UNIQUE AND FOREIGN KEY CONSTRAINTS 
ALTER TABLE USER_SESSION ADD CONSTRAINT USER_SESSION_PK PRIMARY KEY (ID)  USING INDEX;

-- SEQUENCE
CREATE SEQUENCE  USER_SESSION_SEQ;

-- TRIGGER
CREATE OR REPLACE TRIGGER USER_SESSION_BI BEFORE INSERT ON USER_SESSION FOR EACH ROW
BEGIN
	:NEW.ID := USER_SESSION_SEQ.NEXTVAL;
END USER_SESSION_BI;
/