-- CREATE TABLE
CREATE TABLE CREDENTIAL
(
	ID             		NUMBER(18) NOT NULL,
	USER_NAME			VARCHAR2(256) NOT NULL,
	PASSWORD			VARCHAR2(128) NOT NULL,
	ENTITY_TYPE			INTEGER NOT NULL,
	ENTITY_ID			NUMBER(18) NOT NULL,
	CREATED_TIMESTAMP	DATE NOT NULL,
	EXPIRY_TIMESTAMP	DATE NOT NULL,
	CREDENTIAL_STATUS	INTEGER NOT NULL
);
-- CREATE/RECREATE PRIMARY, UNIQUE AND FOREIGN KEY CONSTRAINTS 
ALTER TABLE CREDENTIAL ADD CONSTRAINT CREDENTIAL_PK PRIMARY KEY (ID)  USING INDEX;

-- SEQUENCE
CREATE SEQUENCE  CREDENTIAL_SEQ;

-- TRIGGER
CREATE OR REPLACE TRIGGER CREDENTIAL_BI BEFORE INSERT ON CREDENTIAL FOR EACH ROW
BEGIN
	:NEW.ID := CREDENTIAL_SEQ.NEXTVAL;
END CREDENTIAL_BI;
/
